env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
gomod:
  proxy: true
builds:
  - main:
      ./cmd/facc/
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/srobroek/facc/internal/facc/cli.version={{.Version}} -X github.com/srobroek/facc/internal/facc/cli.commit={{.Commit}} -X github.com/srobroek/facc/internal/facc/cli.date={{ .CommitDate }} -X github.com/srobroek/facc/internal/facc/cli.builtBy=goReleaser
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^ci'
      - '^refactor'
      - Merge pull request
      - Merge branch
      - go mod tidy
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
    format_overrides:
      - goos: windows
        format: zip
